spring:
  application:
    name: polizas
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    h2:
      console:
        enabled: true
        path: /h2-console
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: sa
      password:
      platform: h2
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true