server:
  port: 8083
spring:
  application:
    name: polizas
  r2dbc:
    url: r2dbc:postgres://xowpqsqr:CepDVR5eh-tipHIRCMSafCGFPVWIes3U@kala.db.elephantsql.com/xowpqsqr
    username: postgres
    password: admin
    pool:
      enabled: true
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true